owner: justlogincom
repo: status

sites:
  - name: Login API
    url: $JUSTLOGIN_LOGIN_API_URL
    method: POST
    headers:
      - "Content-Type: application/x-www-form-urlencoded"
    body: $JUSTLOGIN_LOGIN_API_BODY
  - name: Login Page
    url: $JUSTLOGIN_LOGIN_PAGE_URL
  - name: Commercial Site
    url: $JUSTLOGIN_COMMERCIAL_SITE_URL

status-website:
  cname: status.justlogin.com
  favicon: https://justlogin.com/wp-content/uploads/2024/12/cropped-justlogin-plane-512px-192x192.png
  logoUrl: https://justlogin.com/wp-content/uploads/2020/09/justlogin-logo-200px.png
  name: JustLogin Status Page
  introTitle: "JustLogin | AI-Powered HRMS Software | 25 Years Of HR Expertise"
  introMessage: This is the status page for JustLogin, an AI powered HRMS software.
  navbar:
    - title: Homepage
      href: https://justlogin.com/
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
